### ISSUE TITLE
consult

### ISSUE THREAD

**Issue by bigsu** [pygeoops/pygeoops#104]
Do you know how to extract the spline of a line? like this
![image](https://github.com/user-attachments/assets/541211fe-8c8e-488c-bee4-7d9611bf978d)

**Comment by theroggy** [comment]
I'm afraid I don't have any practical experience with using splines...

**Comment by theroggy** [comment]
Also :not sure what exactly you are looking for based on your image, but this is a library that has a function to use splines for smoothing lines: https://github.com/philipschall/shapelysmooth

Is this what oyu are looking for?

**Comment by bigsu** [comment]
> Also: not sure what exactly you are looking for based on your image, but this is a library that has a function to use splines for smoothing lines: https://github.com/philipschall/shapelysmooth另外：不确定你到底在寻找什么基于你的图像，但这是一个库，有一个功能，使用样条平滑线：https://github.com/philipschall/shapelysmooth
> 
> Is this what oyu are looking for?这就是你要找的吗？
不是的，我希望从道路中心线上提取每条线段的垂线，从而得到合适的道路宽度。我再想一想，再次感谢！
No, I hope to extract the perpendicular line of each line segment from the centerline of the road to obtain the appropriate road width. Let me think about it again. Thanks again!
![image](https://github.com/user-attachments/assets/8d98c68a-72db-4713-be56-35b15c76af00)
