### ISSUE TITLE
IllegalArgumentException: point array must contain 0 or >1 elements

### ISSUE THREAD

**Issue by bigsu** [pygeoops/pygeoops#70]
![image](https://github.com/pygeoops/pygeoops/assets/18549401/dd6c1730-6a5f-4ae5-ba8b-ce3c7a21214a)
Why does this happen?
shapely.errors.GEOSException: IllegalArgumentException: point array must contain 0 or >1 elements

[road-buffer-14-26969-4551.zip](https://github.com/pygeoops/pygeoops/files/13765026/road-buffer-14-26969-4551.zip)

**Comment by bigsu** [comment]
This exception is a special case, and I can succeed for the most part
![image](https://github.com/pygeoops/pygeoops/assets/18549401/8789dee9-520d-4336-98c3-cbc102b0c672)

maybe this answer is helpful to you
[](https://github.com/geopandas/geopandas/issues/2791)

**Comment by bigsu** [comment]
I try to set densify_distance to 1 to see if it avoids the error.
`centerline = pygeoops.centerline(input_geom, 1, -3, -0.1)`

**Comment by bigsu** [comment]
自问自答，兄弟们

**Comment by theroggy** [comment]
You found a workaround yourself, but FYI: I'm not able to reproduce the issue you had. I think this issue was solved in #60, so posibly you are using an old version of pygeoops.

**Comment by bigsu** [comment]
> Great you found a workaround!太好了，你找到了一个解决方法！
> 
> But, FYI: I'm not able to reproduce the issue you had. I think this issue was solved in #60, so possibly you are using an old version of pygeoops.但是，仅供参考：我无法重现您遇到的问题。我认为这个问题已在 #60 中解决，因此您可能正在使用旧版本的 pygeoops。

I used pip to install but I don't know if it is the latest code
