### ISSUE TITLE
The centerline is not really centered

### ISSUE THREAD

**Issue by jmonticolo** [pygeoops/pygeoops#86]
The [`centerline` function](https://pygeoops.readthedocs.io/en/latest/api/pygeoops.centerline.html#pygeoops.centerline) gives a result that is not fine enough, which means that the line isn't centered everywhere, see the screencapture below.

Different parameters were tested, mainly `densify_distance`, but with no satisfying result.

To reproduce:
```py
import pygeoops
import shapely


with open("rhin_tortu.geojson", "r") as input:
    polygon = shapely.from_geojson(input.read())

with open("centerline.geojson", "w") as output:
    centerline = pygeoops.centerline(polygon)
    output.write(shapely.to_geojson(centerline))

```

![image](https://github.com/pygeoops/pygeoops/assets/20857031/8ee11868-25a4-4142-b944-3945738cad1f)

GeoJSON: [rhin_tortu.zip](https://github.com/user-attachments/files/15774038/rhin_tortu.zip)

**Comment by theroggy** [comment]
The detail of the result is determined by two parameters: `densify_distance` and `simplifytolerance`.

This is an example output when both are finetuned for your case (red=default, green=finetuned):

![image](https://github.com/pygeoops/pygeoops/assets/1565789/2c9b1bb3-a605-434d-a762-82ab6cda42c5)

Code:
``` py
from matplotlib import pyplot as plt
import pygeoops
import shapely
import shapely.plotting

with open("c:/temp/rhin_tortu.geojson") as input:
    polygon = shapely.from_geojson(input.read()).geoms[0]

centerline_default = pygeoops.centerline(polygon)
centerline2 = pygeoops.centerline(
    polygon, densify_distance=0.00001, simplifytolerance=0.000005
)

_, ax = plt.subplots()
shapely.plotting.plot_polygon(polygon, ax=ax, color="blue", linewidth=1)
shapely.plotting.plot_line(centerline_default, ax=ax, color="red", linewidth=1)
shapely.plotting.plot_line(centerline2, ax=ax, color="green", linewidth=1)
plt.show()
```

**Comment by jmonticolo** [comment]
Thanks for your explanation and time, it worked perfectly.
